apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: ping
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: ping
        tier: backend
    spec:
      containers:
        - name: backend
          image: backend:latest
          ports:
            - name: http
              containerPort: 8080