apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: ping
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: ping
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: frontend:latest
          env:
            - name: NEXT_PUBLIC_BACKEND_URL
              value: "http://backend:8080"
          imagePullPolicy: Never  # keep enabled while using minikube locally
          ports:
            - containerPort: 3000